name: evagg
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - python>=3.12.4
  - poetry>=1.8.3

  # Scientific computing.
  - numpy==2.0.0
  - pandas==2.2.2
  - pyarrow==16.1.0 # Required by pandas.
  - openpyxl==3.1.4 # To work with Excel files in pandas.
  - ipykernel==6.29.5 # IPython kernel for jupyter.
  - jinja2==3.1.4 # Required for jupyter notebooks.
  - ipywidgets==8.1.3 # Support for widgets in jupyter notebooks.
  - matplotlib==3.8.4
  - seaborn==0.13.2
  - plotly==5.22.0

  # General utilities.
  - pydantic==1.10.16
  - defusedxml==0.7.1
  - ratelimit==2.2.1
  - python-dotenv==1.0.1
  - urllib3==2.2.2
  - azure-cosmos==4.6.0
  - azure-identity==1.17.1
  - gh==2.52.0

  # AI/ML.
  - openai==1.35.10
  - httpx==0.27.0 # Greater than this breaks openai 1.35.
  - scikit-learn==1.5.1

  # Bioinformatics.
  - biopython==1.84

  # Dependencies used for code development (linting, testing, etc.)
  - black==24.4.2
  - isort==5.13.2
  - flake8==7.1.0
  - pep8-naming==0.14.1
  - flake8-bugbear==24.4.26
  - flake8-comprehensions==3.15.0
  - flake8-docstrings==1.7.0
  - flake8-eradicate==1.5.0
  - flake8-noqa==1.4.0
  - flake8-isort==6.1.1
  - flake8-black==0.3.6
  - bandit==1.7.8
  - mypy==1.10.1
  - types-requests==2.32.0.*
  - types-pyyaml==6.0.12.*
  - types-retry==0.9.9.*
  - pytest==8.2.2
  - pytest-cov==5.0.0
  - pytest-mock==3.14.0
  - pytest-asyncio==0.23.7

  # pip dependencies. Before adding a package to this list, make sure it's not available in conda.
  - pip==24.0
  - pip:
    - hpo3==1.3.1
