name: evagg
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - python>=3.12
  - poetry>=1.2

  # Scientific computing.
  - numpy
  - pandas
  - openpyxl # To work with Excel files in pandas.
  - ipykernel # IPython kernel for jupyter.
  - jinja2 # Required for jupyter notebooks.
  - ipywidgets # Support for widgets in jupyter notebooks.
  - matplotlib
  - seaborn

  # General utilities.
  - pydantic==1.10.*
  - defusedxml
  - ratelimit
  - retry
  - python-dotenv
  - urllib3
  - azure-cosmos
  - gh

  # AI/ML.
  - openai

  # Bioinformatics.
  - biopython

  # Dependencies used for code development (linting, testing, etc.)
  - black
  - isort
  - flake8
  - pep8-naming
  - flake8-bugbear
  - flake8-comprehensions
  - flake8-docstrings
  - flake8-eradicate
  - flake8-noqa
  - flake8-isort
  - flake8-black
  - bandit
  - mypy
  # - types-python-dateutil
  - types-requests
  - types-pyyaml
  - types-retry
  - pytest
  - pytest-cov
  - pytest-mock
  #? - snakeviz

  # # pip dependencies. Before adding a package to this list, make sure it's not available in conda.
  # - pip
  # - pip:
  #   - semantic-kernel
  #   # do not change the pydantic version here, this is specified identically to the pydantic req above, forcing pip to leave it alone.
  #   - pydantic==1.10.*
