# Keywords
INCLUSION_KEYWORDS = [
    "variant",
    "variants",
    "rare disease",
    "rare diseases",
    "rare variant",
    "rare variants",
    "disorder",
    "disorders",
    "syndrome",
    "syndromes",
    "-emia",
    "-emias",
    "-cardia",
    "-cardias",
    "-phagia",
    "-phagias",
    "pathogenic",
    "pathogenics",
    "benign",
    "benigns",
    "inherited cancer",
    "inherited cancers",
    "germline",
    "germlines",
    "-lepsy",
    "-lepsies",
    "-pathy",
    "-pathies",
    "-osis",
    "-oses",
    "variant of unknown significance",
    "variants of unknown significance",
    "variant of uncertain significance",
    "variants of uncertain significance",
    "mendelian",
    "monogenic",
    "monogenicity",
    "monoallelic",
    "syndromic",
    "inherited",
    "hereditary",
    "dominant",
    "recessive",
    "de novo",
    "VUS",
    "disease causing",
]

EXCLUSION_KEYWORDS = [
    "digenic",
    "structural variant",
    "structural variants",
    "somatic",
    "somatic cancer",
    "somatic cancers",
    "cancer",
    "cancers",
    "CNV",
    "CNVs",
    "copy number variant",
    "copy number variants",
]
